package DMMS;


/**
* DMMS/CORBAInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMMS.idl
* Saturday, April 1, 2023 12:18:39 o'clock PM EDT
*/

abstract public class CORBAInterfaceHelper
{
  private static String  _id = "IDL:DMMS/CORBAInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, DMMS.CORBAInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DMMS.CORBAInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DMMS.CORBAInterfaceHelper.id (), "CORBAInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DMMS.CORBAInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CORBAInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DMMS.CORBAInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DMMS.CORBAInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DMMS.CORBAInterface)
      return (DMMS.CORBAInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DMMS._CORBAInterfaceStub stub = new DMMS._CORBAInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DMMS.CORBAInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DMMS.CORBAInterface)
      return (DMMS.CORBAInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DMMS._CORBAInterfaceStub stub = new DMMS._CORBAInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
