package DMMS;


/**
* DMMS/CORBAInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMMS.idl
* Saturday, April 1, 2023 12:18:39 o'clock PM EDT
*/

public abstract class CORBAInterfacePOA extends org.omg.PortableServer.Servant
 implements DMMS.CORBAInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addMovieSlots", new java.lang.Integer (0));
    _methods.put ("removeMovieSlots", new java.lang.Integer (1));
    _methods.put ("listMovieShowsAvailability", new java.lang.Integer (2));
    _methods.put ("bookMovieTickets", new java.lang.Integer (3));
    _methods.put ("cancelMovieTickets", new java.lang.Integer (4));
    _methods.put ("getBookingSchedule", new java.lang.Integer (5));
    _methods.put ("exchangeTickets", new java.lang.Integer (6));
    _methods.put ("shutdown", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DMMS/CORBAInterface/addMovieSlots
       {
         String adminID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         String quantity = in.read_string ();
         String $result = null;
         $result = this.addMovieSlots (adminID, movieID, movieName, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // DMMS/CORBAInterface/removeMovieSlots
       {
         String adminID = in.read_string ();
         String movieID = in.read_string ();
         String quantity = in.read_string ();
         String $result = null;
         $result = this.removeMovieSlots (adminID, movieID, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // DMMS/CORBAInterface/listMovieShowsAvailability
       {
         String adminID = in.read_string ();
         String movieName = in.read_string ();
         String $result = null;
         $result = this.listMovieShowsAvailability (adminID, movieName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // DMMS/CORBAInterface/bookMovieTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         String numberOfTickets = in.read_string ();
         String $result = null;
         $result = this.bookMovieTickets (customerID, movieID, movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // DMMS/CORBAInterface/cancelMovieTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         String numberOfTickets = in.read_string ();
         String $result = null;
         $result = this.cancelMovieTickets (customerID, movieID, movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // DMMS/CORBAInterface/getBookingSchedule
       {
         String customerID = in.read_string ();
         String $result = null;
         $result = this.getBookingSchedule (customerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // DMMS/CORBAInterface/exchangeTickets
       {
         String customerID = in.read_string ();
         String newmovieID = in.read_string ();
         String oldmovieID = in.read_string ();
         String newmovieName = in.read_string ();
         String numberOfTickets = in.read_string ();
         String oldmovieName = in.read_string ();
         String $result = null;
         $result = this.exchangeTickets (customerID, newmovieID, oldmovieID, newmovieName, numberOfTickets, oldmovieName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // DMMS/CORBAInterface/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DMMS/CORBAInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CORBAInterface _this() 
  {
    return CORBAInterfaceHelper.narrow(
    super._this_object());
  }

  public CORBAInterface _this(org.omg.CORBA.ORB orb) 
  {
    return CORBAInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class CORBAInterfacePOA
